### PR TITLE
Implementation for proposed enhancement for Midweek resets

### PR DESCRIPTION
**Pull request by JoeLatte88**
Implemented my proposed enhancement for Midweek resets, also updated some formatting to allow for the added option.
https://github.com/peterwooley/Todo/issues/2

### CODE REVIEW

**Comment by JoeLatte88** [comment]
image
image
image

**Comment by JoeLatte88** [comment]
@peterwooley, let me know your thoughts when you get a chance :)

**Comment by peterwooley** [comment]
Oh yeah, this is great! I've just looked at the screenshots and code, so I'll run it later this evening and let you know if I find any issues. If it's all clear, I'll pull it in. Thanks for doing this work!

**Comment by peterwooley** [comment]
I had one issue while upgrading from 1.0.11 and added a check for others upgrading. Everything else I tried worked like a charm. Thanks again for your work here! This was also the first time I've pushed a change to a pull request ahead of the merge. I didn't know that worked!

**Comment by peterwooley** [comment]
After a few days dealing with CurseForge’s automatic build system, the midweek feature is now live in 1.1.0. Thanks, again!

**Pull request merged**
